### ISSUE TITLE
Kernel unpack errors

### ISSUE THREAD

**Issue by kennyliveforever** [notro/rpi-source#38]
Hello! Help me please
```
*** Unpack kernel source
.............................................tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/powerpc/boot/dts/include: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/powerpc/boot/dts: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/powerpc/boot: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/powerpc: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/mips/boot/dts/include: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/mips/boot/dts: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/mips/boot: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/mips: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/metag/boot/dts/include: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/metag/boot/dts: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/metag/boot: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/metag: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/cris/boot/dts/include: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/cris/boot/dts: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/cris/boot: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/cris: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/arm64/boot/dts/socionext: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/arm64/boot/dts/include: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/arm64/boot/dts/broadcom: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/arm64/boot/dts/arm: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/arm64/boot/dts: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/arm64/boot: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/arm64: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/arm/boot/dts/include: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/arm/boot/dts: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/arm/boot: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch/arm: Directory renamed before its status could be extracted
tar: linux-a2f34d45809d8685bca1e91989e35746499ac400/arch: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
Traceback (most recent call last):
  File "/usr/bin/rpi-source", line 345, in <module>
    sh("cd %s && tar --checkpoint=100 --checkpoint-action=dot -xzf %s" % (args.dest, linux_tar))
  File "/usr/bin/rpi-source", line 85, in sh
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /root && tar --checkpoint=100 --checkpoint-action=dot -xzf /root/linux-a2f34d45809d8685bca1e91989e35746499ac400.tar.gz' returned non-zero exit status 2

```
How fix it?

**Comment by mikeza** [comment]
Also experiencing this
